---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/1/1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/218941/articles/280589/master/file/figures/1/1.png"
    folder_url: "/users/218941/articles/280589/master/folder/figures/1"
