---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/a/a.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/218941/articles/280589/master/folder/figures/a"
    url: "/users/218941/articles/280589/master/file/figures/a/a.png"
