---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Scan_20180207 (2)/Scan_20180207 (2).png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/218941/articles/280589/master/file/figures/Scan_20180207%20(2)/Scan_20180207%20(2).png"
