---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Copy of CONSUMABLES/figures_Copy of CONSUMABLES_Copy of CONSUMABLES.xlsx
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/218941/articles/280589/master/folder/figures/Copy of CONSUMABLES"
    url: "/users/218941/articles/280589/master/file/figures/Copy%20of%20CONSUMABLES/figures_Copy%20of%20CONSUMABLES_Copy%20of%20CONSUMABLES.xlsx"
