---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Copy of CONSUMABLES (non food items)/Copy of CONSUMABLES (non food
      items).xlsx
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/218941/articles/280589/master/file/figures/Copy%20of%20CONSUMABLES%20(non%20food%20items)/Copy%20of%20CONSUMABLES%20(non%20food%20items).xlsx"
    folder_url: "/users/218941/articles/280589/master/folder/figures/Copy of CONSUMABLES
      (non food items)"
