---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/a1/figures_a1_a1.xlsx
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/218941/articles/280589/master/folder/figures/a1"
    url: "/users/218941/articles/280589/master/file/figures/a1/figures_a1_a1.xlsx"
